//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SailorsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HarbourMembers
    {
        public int memberId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> userScoutRank { get; set; }
        public Nullable<System.DateTime> userBirthDate { get; set; }
        public string userScoutNumber { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ScoutRanks ScoutRanks { get; set; }
    }
}
