//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SailorsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int postId { get; set; }
        public string postText { get; set; }
        public string userPosting { get; set; }
        public Nullable<System.DateTime> postDate { get; set; }
        public byte[] postImage { get; set; }
        public Nullable<int> userPostingId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
