//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SailorsWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HowDatabaseEntities : DbContext
    {
        public HowDatabaseEntities()
            : base("name=HowDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EquipmentTypes> EquipmentTypes { get; set; }
        public virtual DbSet<Functions> Functions { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<SailingEquipment> SailingEquipment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<HabourRenting> HabourRenting { get; set; }
        public virtual DbSet<RentingEquipment> RentingEquipment { get; set; }
    }
}
